### ISSUE TITLE
qr code not generated

### ISSUE THREAD

**Issue by Nawkyooo** [justacoincidence/Discord-QR-Grabber-Bot#6]
![image](https://user-images.githubusercontent.com/132665395/236439905-b46d36f2-f001-4c7d-bf4f-414433b62770.png)

qr_code = div.find('img')['src']
TypeError: 'NoneType' object is not subscriptable

**Comment by Nawkyooo** [comment]
2023-05-05 12:49:40 ERROR    discord.ext.commands.bot Ignoring exception in command verify
Traceback (most recent call last):
  File "C:\Users\mathd\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 229, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\mathd\Desktop\Discord-QR-Grabber-Bot-main\main.py", line 83, in verify
    qr_code = div.find('img')['src']
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\mathd\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 1349, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\mathd\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 1023, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\mathd\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 238, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable

**Comment by xilencen-sketch** [comment]
did you figure it out i need help

**Comment by keosp8** [comment]
It didn’t find the qr code in the discord login page try to make prints to see whe div or it just renders with Java script..
